<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    use HasFactory;

    protected $fillable = ["name", "excerpt", "content"];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::created(function($table) {
            if(!app()->runningInConsole()) {
                $table->user_id = auth()->id();
            }
        });
    }

    public function user() {
        return $this->belongsTo(User::class);
    }

    public function scopeFilter(Builder $query, array $filters){
        if(!request("page")) {
            session()->put("search", $filters['search'] ?? null);
            session()->put("trashed", $filters['trashed'] ?? null);
        }

        $query->when(session("search"), function ($query, $search){
            $query->where("name", 'LIKE', '%'.$search.'%');
        })->when(session("trashed"), function ($query, $trashed) {
            if($trashed === 'with') {
                $query->withTrashed();
            } elseif ($trashed === 'only') {
                $query->onlyTrashed();
            }
        });
    }
}
